lib/result-gather.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/4)
=> debug url fix

lib/api-server.js, lib/server.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/6)
=> add pasue/resume

lib/etcd-data.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/10)
=> fix: PR commit

lib/service/redis-storage-adapter.js, lib/service/result-gather.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/13)
=> fix: improve graph

lib/node-statistics/statistics.js, lib/service/server.js, lib/task-logs/logs.js, package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/15)
=> Fix memory in UI. Select log source in query string

lib/service/etcd-data.js, lib/service/result-gather.js, lib/service/server.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/14)
=> Experiment

lib/service/board.js, lib/service/etcd-data.js, lib/service/result-gather.js, package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/16)
=> Provide access to boards

lib/service/board.js, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/17)
=> upgrade storage-manager

lib/service/etcd-data.js, lib/service/server.js
add experiment name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/18)
=> add show-all dummy experiment

.gitignore, config/main/config.base.js, lib/service/server.js, package-lock.json, package.json, scripts/build-branch.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/20)
=> feature: encoding, storage

.travis.yml, dockerfile/Dockerfile, package-lock.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/22)
=> update to node 14

lib/node-statistics/statistics.js, lib/service/result-gather.js, package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/23)
=> feat: add disk usage

lib/service/server.js
Prevent crash if experiment name is empty (null)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/24)
=> add default experiment

bootstrap.js, config/main/config.base.js, lib/node-statistics/statistics.js, lib/service/HttpError.js, lib/service/etcd-data.js, lib/service/gather-pipelines-stats.js, lib/service/redis-storage-adapter.js, lib/service/result-gather.js, lib/service/server.js, package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/28)
=> feat: db migration

lib/service/etcd-data.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/30)
=> feat: add user pipeline

.dockerignore, .eslintrc.js, dockerfile/Dockerfile, lib/node-statistics/statistics.js, lib/service/board.js, lib/service/gather-pipelines-stats.js, lib/service/result-gather.js, lib/service/server.js, lib/task-logs/es.js, lib/task-logs/kubernetes.js, lib/task-logs/logs.js, lib/task-logs/searchComponents.js, lib/utils/error-response.js, package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/32)
=> add logs from datasource

bootstrap.js, config/main/config.base.js, lib/service/result-gather.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/33)
=> delete flow input of too large

.eslintrc.js, lib/service/etcd-data.js, lib/service/server.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/34)
=> add endpoint for original flow input

lib/service/etcd-data.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/35)
=> feat: size limit

lib/service/server.js, lib/task-logs/logs.js, package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/36)
=> filter internal logs

lib/service/etcd-data.js, lib/service/graph-data.js, lib/service/redis-storage-adapter.js, lib/service/result-gather.js, package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/37)
=> move graph to mongo

dockerfile/build.sh, lib/service/etcd-data.js, lib/service/gather-pipelines-stats.js, lib/service/result-gather.js, lib/utils/tracing.js, package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/38)
=> optimize mongo query

config/main/config.base.js, lib/service/result-gather.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/39)
=> toggle metrics for streaming

package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/40)
=> updated hkube/db version

lib/service/server.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/42)
=> fix room register

lib/node-statistics/statistics.js, lib/service/HttpError.js, lib/service/board.js, lib/service/gather-pipelines-stats.js, lib/service/redis-storage-adapter.js, lib/service/server.js, lib/task-logs/es.js, lib/task-logs/kubernetes.js, lib/utils/error-response.js, package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/50)
=> fluent-for-1-3

lib/service/etcd-data.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/53)
=> feat: force flowInput download

config/main/config.base.js, lib/service/server.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/58)
=> add queue proxy

config/main/config.base.js, lib/consts/components.js, lib/jaeger/jaeger-api.js, lib/service/gather-pipelines-stats.js, lib/service/result-gather.js, package-lock.json, package.json
add queue size api
switch to axios
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/60)
=> add queue size api

dockerfile/Dockerfile, package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-hpc/monitor-server/64)
=> update packages for node 18
